export const GET_REPORT_DEVICE = "GET_REPORT_DEVICE";
export const POST_REPORT_DEVICE = "POST_REPORT_DEVICE";
export const PUT_REPORT_DEVICE = "PUT_REPORT_DEVICE";
export const DELETE_REPORT_DEVICE = "DELETE_REPORT_DEVICE";
export const POST_AND_GET_REPORT_DEVICE = "POST_AND_GET_REPORT_DEVICE";
export const PUT_AND_GET_REPORT_DEVICE = "PUT_AND_GET_REPORT_DEVICE";
export const DELETE_AND_GET_REPORT_DEVICE = "DELETE_AND_GET_REPORT_DEVICE";
export const UPDATE_REPORT_DEVICE_STORAGE = "UPDATE_REPORT_DEVICE_STORAGE";