export const GET_CLIENT = "GET_CLIENT";
export const POST_CLIENT = "POST_CLIENT";
export const PUT_CLIENT = "PUT_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const POST_AND_GET_CLIENT = "POST_AND_GET_CLIENT";
export const PUT_AND_GET_CLIENT = "PUT_AND_GET_CLIENT";
export const DELETE_AND_GET_CLIENT = "DELETE_AND_GET_CLIENT";
export const UPDATE_CLIENT_STORAGE = "UPDATE_CLIENT_STORAGE";