/* USERS */
export const GET_EVENTOS = "GET_EVENTOS"
export const GET_EVENTOS_POR_ELEMENTO = "GET_EVENTOS_POR_ELEMENTO"
export const INSERT_EVENTO = "INSERT_EVENTO"
export const INSERT_EVENTO_A_ELEMENTO = "INSERT_EVENTO_A_ELEMENTO"
export const EDIT_EVENTO = "EDIT_EVENTO"
export const WAIT_EVENTOS = "WAIT_EVENTOS"
export const GET_EVENTOS_SUCCESS = "GET_EVENTOS_SUCCESS"
export const GET_EVENTOS_FAIL = "GET_EVENTOS_FAIL"
