export const GET_M_BRAND = "GET_M_BRAND";
export const POST_M_BRAND = "POST_M_BRAND";
export const PUT_M_BRAND = "PUT_M_BRAND";
export const DELETE_M_BRAND = "DELETE_M_BRAND";
export const POST_AND_GET_M_BRAND = "POST_AND_GET_M_BRAND";
export const PUT_AND_GET_M_BRAND = "PUT_AND_GET_M_BRAND";
export const DELETE_AND_GET_M_BRAND = "DELETE_AND_GET_M_BRAND";
export const UPDATE_STORAGE = "UPDATE_STORAGE";