/* USERS */
export const GET_CLIENTES = "GET_CLIENTES"
export const INSERT_CLIENTE = "INSERT_CLIENTE"
export const EDIT_CLIENTE = "EDIT_CLIENTE"
export const WAIT_CLIENTES = "WAIT_CLIENTES"
export const GET_CLIENTES_SUCCESS = "GET_CLIENTES_SUCCESS"
export const GET_CLIENTES_FAIL = "GET_CLIENTES_FAIL"
