/* USERS */
export const GET_VEHICULOS = "GET_VEHICULOS"
export const INSERT_VEHICULO = "INSERT_VEHICULO"
export const INSERT_MODEM_A_VEHICULO = "INSERT_MODEM_A_VEHICULO"
export const REMOVE_MODEM = "REMOVE_MODEM"
export const EDIT_VEHICULO = "EDIT_VEHICULO"
export const WAIT_VEHICULOS = "WAIT_VEHICULOS"
export const GET_VEHICULOS_SUCCESS = "GET_VEHICULOS_SUCCESS"
export const GET_VEHICULOS_FAIL = "GET_VEHICULOS_FAIL"
