export const GET_PLATFORM_COUNT = "GET_PLATFORM_COUNT";
export const POST_PLATFORM_COUNT = "POST_PLATFORM_COUNT";
export const PUT_PLATFORM_COUNT = "PUT_PLATFORM_COUNT";
export const DELETE_PLATFORM_COUNT = "DELETE_PLATFORM_COUNT";
export const POST_AND_GET_PLATFORM_COUNT = "POST_AND_GET_PLATFORM_COUNT";
export const PUT_AND_GET_PLATFORM_COUNT = "PUT_AND_GET_PLATFORM_COUNT";
export const DELETE_AND_GET_PLATFORM_COUNT = "DELETE_AND_GET_PLATFORM_COUNT";
export const UPDATE_PLATFORM_COUNT_STORAGE = "UPDATE_PLATFORM_COUNT_STORAGE";