/* USERS */
export const GET_DISPOSITIVOS = "GET_DISPOSITIVOS"
export const INSERT_DISPOSITIVO = "INSERT_DISPOSITIVO"
export const EDIT_DISPOSITIVO = "EDIT_DISPOSITIVO"
export const WAIT_DISPOSITIVOS = "WAIT_DISPOSITIVOS"
export const GET_DISPOSITIVOS_SUCCESS = "GET_DISPOSITIVOS_SUCCESS"
export const GET_DISPOSITIVOS_FAIL = "GET_DISPOSITIVOS_FAIL"
export const DISPOSITIVO_RETIRAR_SIM = "DISPOSITIVO_RETIRAR_SIM"
