export const GET_PLATFORM = "GET_PLATFORM";
export const POST_PLATFORM = "POST_PLATFORM";
export const PUT_PLATFORM = "PUT_PLATFORM";
export const DELETE_PLATFORM = "DELETE_PLATFORM";
export const POST_AND_GET_PLATFORM = "POST_AND_GET_PLATFORM";
export const PUT_AND_GET_PLATFORM = "PUT_AND_GET_PLATFORM";
export const DELETE_AND_GET_PLATFORM = "DELETE_AND_GET_PLATFORM";
export const UPDATE_PLATFORM_STORAGE = "UPDATE_PLATFORM_STORAGE";