/* USERS */
export const GET_USUARIOS = "GET_USUARIOS"
export const INSERT_USUARIO = "INSERT_USUARIO"
export const EDIT_USUARIO = "EDIT_USUARIO"
export const WAIT_USUARIOS = "WAIT_USUARIOS"
export const GET_USUARIOS_SUCCESS = "GET_USUARIOS_SUCCESS"
export const GET_USUARIOS_FAIL = "GET_USUARIOS_FAIL"
